server {
    listen 80;

    server_name localhost;

    location /climawear/ {
        proxy_pass http://app-climawear:3000/;    # apps1 service name = 'web'
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /fastapi/ {
        proxy_pass http://api:8000/;    # apps1 service name = 'web'
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}